지문 렌더, 간단한 문제 풀이 UI
riiicruitwww/render-passage-algoshipda pull request #3
Opened 2019-04-07 14:14 UTC by algoshipda

- 지문 레더
https://github.com/riiicruitwww/render-passage-algoshipda/blob/master/README.md
와 비슷한 형태로 렌더하는 것을 목표로 했습니다.

- 문제풀이 UI
문제마다 답을 모두  고르면 Submit 버튼이 활성화되고, Submit 버튼을 클릭하면
정답여부에 따라 문제영역에 초록(O), 빨강(X) 테투리가 보입니다.
테두리가 있는 상태에서 다시 정답을 선택하면 테두리가 사라집니다. (Submit을 누르면 다시 생깁니다.)
![image](https://user-images.githubusercontent.com/12122155/55684819-9fa10680-598a-11e9-90e9-bf50a78c989f.png)

(모바일 기기 환경에 대해서는 따로 고려하지 않은 상태라 레이아웃이 안맞을 수 있습니다.)
[18.191.191.178](http://18.191.191.178) 로 접속하시면 볼 수 있습니다.

2019-04-07 15:27 UTC, vchoisk commented
정말 수고 많으셨습니다. 저희가 내일 혹은 모래 중으로 리뷰후에 다시 @algoshipda 달아서 알려드리겠습니다.

2019-04-08 03:07 UTC, shKwonRiiid requested changes

2019-04-08 03:07 UTC, shKwonRiiid commented on src/components/renderer-mapper.tsx
> +type IViewTreeItemRenderer<T extends IViewTreeItem> = (item: T, i: string | number) => JSX.Element;
`i` 가 string인 경우는 어떤경우인가요?

2019-04-08 03:07 UTC, shKwonRiiid commented on typings/passage.d.ts
> +declare type IChunk = {
네이밍에 `I`가 interface를 의미하는건줄 알았는데 잘못이해했나요?

`I`의미가 뭔지 알려주실수 있나요? 😃

2019-04-08 03:07 UTC, shKwonRiiid commented on src/actions/index.ts
> +  passages: IPassage[],
IPassage 뒤에 `[]`  의미가 무엇인가요?

2019-04-08 03:07 UTC, shKwonRiiid commented on src/actions/index.ts
> +  passages: IPassage[],
IPassage 를 지닌 배열이라는것을 명시하는건가요?

2019-04-08 05:36 UTC, vchoisk requested changes

2019-04-08 05:36 UTC, vchoisk commented on src/components/cell.tsx
> +  data: ICell;
props 명은 조금더 명시적으로  `data => cell`로 하면 어떨까요?

2019-04-08 05:36 UTC, vchoisk commented on src/components/renderer-mapper.tsx
> +export default function rendererMapper<T extends IViewTreeItem>(item: T, i: string | number): JSX.Element {
mapper로 돌리기보다 
```
switch(item.name) {
  case: 'paragraph':
    return <ParagraphView key={i} date={item}/>
  ...
  default:
    return null
}
```
처럼 switch syntax 사용하면 어떨까요?

2019-04-08 05:36 UTC, vchoisk commented on src/components/chunk.tsx
> +)(function ChunkView({ data, chunk }: IChunkViewProps): JSX.Element {
따로 컴포넌트 정의하고 인자로 넘겨주면 어떨가요?

Test할 때에도 원하면  connect안된 상태로 import해서 테스트 할수도있고 ㅎㅎ

2019-04-08 05:36 UTC, vchoisk commented on src/components/chunk.tsx
> +function toRGB([r, g, b]: [number, number, number]) {
요런 함수는 util 함수로 따로 빼면 어떨까요?

2019-04-08 05:36 UTC, vchoisk commented on src/components/app.tsx
> +  (dispatch: Dispatch) => {
```
{
  onSubmit: submit
}
```

으로 connect두번째 인자는 오브젝트로 넘길수 있어요! ㅎㅎ

2019-04-08 05:36 UTC, vchoisk commented on src/components/chunk.tsx
> +const defaultChunkStyle: CSSProperties = {
이런 정의를 컴포넌트 안과 밖에서 하시는 기준이 있으신가요?

2019-04-08 07:17 UTC, joointhezoo commented on typings/passage.d.ts
> +declare interface IRStyle {
`IRStyle` 이 무엇을 나타내는 네이밍인가요? 🤔

2019-04-08 07:17 UTC, joointhezoo commented on src/components/table.tsx
> +  return <table style={defaultTableStyle}>
라인 내리면 가독성에 더 좋을것 같아요 👓 
```
return (
  <table style={defaultTableStyle}>
    <tbody>{buildTable(tableData}}</tbody>
  </table>
)
```

2019-04-08 07:17 UTC, joointhezoo commented on typings/passage.d.ts
> +declare type RiiidFontColor = 'black'; // ??
불필요한 주석은 제거해주세요 🙏🏻

2019-04-08 08:00 UTC, vchoisk commented
@algoshipda 
작성해주신 코드에 대한 리뷰를 마쳤습니다. 각 코멘트에 대한 소통/반영은 자유롭게 해주시면 감사하겠습니다.
다시 한번 시간내어 기술면접에 응해주셔서 감사드리며 마지막까지 잘 부탁드립니다.

@joointhezoo @shKwonRiiid 🙇 🙇‍♀️ 👍

2019-04-08 13:30 UTC, algoshipda commented on src/components/renderer-mapper.tsx
> +type IViewTreeItemRenderer<T extends IViewTreeItem> = (item: T, i: string | number) => JSX.Element;
array map method에 바로 넘겨서 array의 index를 key로 가져가지 않고,
다른 형태의 key를 사용하길 원할 때 쓰기 위해 만들었습니다.
예를 들어 특정 prefix를 붙이는 형태
```typescript
arr.map((e, i) => rendererMapper(e, `foo_${i}`));
```
라던가
원래 id를 가지고 있는 형태
```typescript
arr.map((e, i) => rendererMapper(e, e.id));
```
같이 쓰일 수 있습니다.
지금 코드에서는 저렇게 쓰이는 부분은 없기때문에 number만 받아도 되기는 합니다.

2019-04-08 13:31 UTC, algoshipda commented on typings/passage.d.ts
> +declare type IChunk = {
`i`는 interface를 의미하는게 맞고 `declare type IChunk = {` -> `declare interface IChunk = {`

2019-04-08 13:33 UTC, algoshipda commented on src/actions/index.ts
> +  passages: IPassage[],
네 각 원소의 타입이 IPassage인 배열을 의미합니다.

2019-04-08 13:35 UTC, algoshipda commented on src/components/app.tsx
> +  (dispatch: Dispatch) => {
해당 내용은 제가 모르는 내용이였네요. 
오브젝트로 넘기는게 나아보입니다. 감사합니다.

2019-04-08 13:37 UTC, algoshipda commented on typings/passage.d.ts
> +declare type RiiidFontColor = 'black'; // ??
네 제거하겠습니다

2019-04-08 13:42 UTC, algoshipda commented on src/components/table.tsx
> +  return <table style={defaultTableStyle}>
네 내리는게 좋아보이네요.
tslint에 `jsx-wrap-multiline` 룰을 넣어서 체크하도록 하겠습니다.

2019-04-08 15:00 UTC, algoshipda commented on src/components/chunk.tsx
> +const defaultChunkStyle: CSSProperties = {
기본적으로 저는 스코프를 좁게 가져가자는 주의로 코드를 작성하지만,
코드 작성시에 이미 결정되는 상수들은 상단에 작성하는걸 선호합니다.
+
tsx 파일 하나와 대응되는 스타일을 기술하는 오브젝트라 다른 코드들과 분리시키고 싶어서 밖으로 빼서 작성했습니다.

2019-04-08 15:08 UTC, algoshipda commented on typings/passage.d.ts
> +declare interface IRStyle {
처음에 IRiiidStyle 정도의 의미로 작성했던 것 같습니다.
사실 IRiiidStyle도 적당한 이름은 아니라.. 다른 좋은 이름 의견 주시면 감사하겠습니다ㅜㅜ

2019-04-08 15:08 UTC, algoshipda commented on src/components/chunk.tsx
> +function toRGB([r, g, b]: [number, number, number]) {
네 지금은 따로 다른데서 쓰는데가 없어서 안뺐는데, 많이 쓰일만 하다면 util로 빼는게 좋겠네요.

2019-04-08 15:11 UTC, algoshipda commented on src/components/chunk.tsx
> +)(function ChunkView({ data, chunk }: IChunkViewProps): JSX.Element {
테스트를 생각한다면 따로 정의하는게 거의 항상 나은 방법이  되겠네요. 고쳐서 반영하도록 하겠습니다.

2019-04-08 15:30 UTC, algoshipda commented on src/components/renderer-mapper.tsx
> +export default function rendererMapper<T extends IViewTreeItem>(item: T, i: string | number): JSX.Element {
mapper를 쓰면 코드가 짧아지지만 data 프로퍼티가 강제되기에 덜 유연한 구조인건 맞습니다.
(처음에 이 구조를 가져간 목적은 지문 데이터에서 사용하는 view_tree 구조에 대한 이해를 덜 하면서 코드를 작성하기 위함이였습니다.)

앱의 규모가커진다면 switch가 거의 모든 경우에 나은 방법일 것이라고는 생각이 듭니다만,
지금 코드에서는 컴포넌트들의 프로퍼티를 변경하고, 타입 정의들을 바꾸는 작업이 같이 들어가지않으면 switch의 장점이 잘 안드러나지 않을까요?

2019-04-08 15:43 UTC, algoshipda commented on src/components/cell.tsx
> +  data: ICell;
rendererMapper에서 안쓰니깐 굳이 data라는 이름을 가져갈 필요는 없겠네요. 수정하겠습니다.

2019-04-08 16:21 UTC, algoshipda commented on src/components/table.tsx
> +  return <table style={defaultTableStyle}>
https://github.com/riiicruitwww/render-passage-algoshipda/pull/3/commits/8e230d56b5fd8a42cd43dac3e2a12c835911c65b 로 처리했습니다

2019-04-08 16:21 UTC, algoshipda commented on typings/passage.d.ts
> +declare interface IRStyle {
https://github.com/riiicruitwww/render-passage-algoshipda/pull/3/commits/8e230d56b5fd8a42cd43dac3e2a12c835911c65b 일단은 IRiiidStyle로 했습니다

2019-04-08 16:26 UTC, algoshipda commented on src/components/app.tsx
> +  (dispatch: Dispatch) => {
https://github.com/riiicruitwww/render-passage-algoshipda/pull/3/commits/4c9ba67e47e3665e412e82beafd78a6b503d1b01#diff-3cfbf771e0ca261b346d338ef93f6982R15
로 고쳤습니다

2019-04-08 16:27 UTC, algoshipda commented on typings/passage.d.ts
> +declare type IChunk = {
https://github.com/riiicruitwww/render-passage-algoshipda/pull/3/commits/4c9ba67e47e3665e412e82beafd78a6b503d1b01#diff-7a95c70f41da5eb0b0eea26ab0a8e7fcR15
수정했습니다

2019-04-08 16:28 UTC, algoshipda commented on src/components/chunk.tsx
> +)(function ChunkView({ data, chunk }: IChunkViewProps): JSX.Element {
https://github.com/riiicruitwww/render-passage-algoshipda/pull/3/commits/4c9ba67e47e3665e412e82beafd78a6b503d1b01
분리했습니다

2019-04-08 16:29 UTC, algoshipda commented on src/components/chunk.tsx
> +function toRGB([r, g, b]: [number, number, number]) {
https://github.com/riiicruitwww/render-passage-algoshipda/commit/94983d37a4673ad6ebc47838f5e407bddb862134
분리했습니다

2019-04-08 16:30 UTC, algoshipda commented on typings/passage.d.ts
> +declare type RiiidFontColor = 'black'; // ??
https://github.com/riiicruitwww/render-passage-algoshipda/pull/3/commits/4c9ba67e47e3665e412e82beafd78a6b503d1b01#diff-7a95c70f41da5eb0b0eea26ab0a8e7fcL6
제거했습니다

2019-04-08 16:33 UTC, algoshipda commented on src/components/cell.tsx
> +  data: ICell;
https://github.com/riiicruitwww/render-passage-algoshipda/pull/3/commits/4c9ba67e47e3665e412e82beafd78a6b503d1b01#diff-768147e3d583b2d73acec7b6d95dcab7R4
수정했습니다

2019-04-09 11:11 UTC, shKwonRiiid commented on src/components/renderer-mapper.tsx
> +type IViewTreeItemRenderer<T extends IViewTreeItem> = (item: T, i: string | number) => JSX.Element;
그렇군요 :)

2019-04-10 02:10 UTC, vchoisk approved these changes

2019-04-10 02:10 UTC, vchoisk commented on src/components/renderer-mapper.tsx
> +export default function rendererMapper<T extends IViewTreeItem>(item: T, i: string | number): JSX.Element {
네 ㅎㅎ 

다른곳에 남긴 코멘트중 data대신 명시적인 props 명을 받는것이 어떨까 하는 것과 함께 바뀌면 좋겠네요 ㅎㅎ

2019-04-10 02:16 UTC, vchoisk commented
@algoshipda
웹팀에서 모든 리뷰를 마쳤습니다. 적지 않은 분량의 기술면접에 성실히 응해주셔서 감사드립니다.

해당 기술 면접을 통해 웹팀원 모두 현석님과 같이 일하고 싶다고 느껴, 훈섭님께 다음과 같이 전달 드렸습니다. 

다음 절차는 훈섭님을 통하여 진행될 예정입니다. 좋은 결과 기다리겠습니다. 🙇 🙇‍♀️

2019-04-10 02:16 UTC, merged